# Generated by Django 4.2.13 on 2024-06-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('act', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='AccessToken',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
