# Generated by Django 4.2.13 on 2024-06-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticator', '0002_person_delete_accesstoken_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='act',
            field=models.CharField(max_length=9),
        ),
    ]
