# Generated by Django 4.2.13 on 2024-06-05 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AZFlag', '0002_flag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
