# Generated by Django 5.0.6 on 2024-07-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AZFlag', '0003_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='anthemURL',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='flag',
            name='uid',
            field=models.IntegerField(default=True),
        ),
    ]
